### PR TITLE
now have a graph

### PR DESCRIPTION
**Pull request by kcpetersen111**

### CODE REVIEW

**Comment by kcpetersen111** [comment]
@starwarsnerd77

**Review by Binary141 — APPROVED** [review]

**Review by starwarsnerd77 — APPROVED** [review]
Good job! Probably will work

**Review by starwarsnerd77 — APPROVED** [review]
Good job! Probably will work

**Review by Razzelz — APPROVED** [review]

**Review by starwarsnerd77 — APPROVED** [review]
Good job! Probably will work

**Pull request merged**
